name: MSEDCL Outage Pipeline

on:
  schedule:
    - cron: '0 6 */7 * *'   # Every 7 days at 6:00 UTC
  workflow_dispatch:        # Manual trigger via UI

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run UrjaDrishti Pipeline
      env:
        RAW_DATA_DIR: data/raw
        CLEAN_DATA_DIR: data/clean
        FETCH_URL: ${{ secrets.FETCH_URL }}
        FETCH_TYPE: ${{ secrets.FETCH_TYPE }}
        USER_AGENT: ${{ secrets.USER_AGENT }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        DATASET_NAME: ${{ secrets.DATASET_NAME }}
        TABLE_NAME: ${{ secrets.TABLE_NAME }}
        GOOGLE_APPLICATION_CREDENTIALS_JSON: ${{ secrets.GCP_KEY }}
      run: |
        echo "$GOOGLE_APPLICATION_CREDENTIALS_JSON" > /tmp/key.json
        export GOOGLE_APPLICATION_CREDENTIALS="/tmp/key.json"
        python main.py
